name: Call Makefile Dispatch

on:
  workflow_dispatch:

jobs:
  no_dependendent_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Makefile
        run: make
