name: Call Makefile Dispatch

on:
  workflow_dispatch:

env:
  PW_BASE_URL: https://playwright.dev/

jobs:

  no_dependendent_check: #This Job will run in parallel with the others, not sequentially
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Print value of gh actions > yml > env
      - name:  env > PW BASE URL
        run: make BASE_URL="${PW_BASE_URL}" no_dependendent_check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: GIT_BRANCH=${GITHUB_REF:11} make test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Can I deploy?
        run: GIT_BRANCH=${GITHUB_REF:11} make can_i_deploy # Extracting a substring: refs/heads/feature/branch-name > ${GITHUB_REF:11} > feature/branch-name
        # make can_i_deploy GIT_BRANCH="main" <- valid as well

  deploy:
    runs-on: ubuntu-latest
    needs: can-i-deploy
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          echo "===== Before Creating .env file ====="
          ls -la
          echo "ENV_VARIABLE=value_var" > .env
          echo "===== AFTER Creating .env file ====="
          ls -la
      - name: Deploy
        run: |
          ls -la
          make deploy